version: 0.2

phases:
  install:
    commands:
      - npm install
      - STAGE=$STAGE REGION=$REGION node seed-restaurants.js
  pre_build:
    commands:
      - npm run test
  build:
    commands:
      - npm run sls -- deploy -s $STAGE -r $REGION
  post_build:
    commands:
      - npm run acceptance