version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run sls -- deploy -s $STAGE -r $REGION
      - STAGE=$STAGE REGION=$REGION node seed-restaurants.js
  post_build:
    commands:
      - npm run test
      - npm run acceptance