version: 0.2

phases:
  build:
    commands:
      - npm install
      - npm run sls -- deploy -s $STAGE -r $REGION
  test:
    commands:
      - npm run test
  acceptance:
    commands:
      - npm run acceptance